version: '2.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 2095:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: changeme
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp-ftp:/var/www/html
    links:
      - db:db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: changeme
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
networks:
  default:
    external:
      name: pihole_private_network
